### PR TITLE
dom7-ajax: code consistency

### PR DESCRIPTION
**Pull request by f0rmat1k**
Hi! A few code consistency enhancement:
— hasOwnProperty is important because just Object.prototype.someMethod = '...'  can break code execution (It can be just shim or users helpers);
— removed unused variables;
— added var paramsPrefix, it has improved two places at code;

### CODE REVIEW

**Comment by nolimits4web** [comment]
Looks good, did you tested it well, nothing breaks?

**Comment by f0rmat1k** [comment]
No i didn't and don't have possibility at the current time.
Also about 'text/javascript'. It isn't required today.

**Comment by nolimits4web** [comment]
Ok, just wondering can you give me a real world example where not checking hasOwnProperty can break things here in XHR?

**Comment by f0rmat1k** [comment]
Yes, you're right, it's not important today. I've checked es6shim and it's don't write into the prototype.

Only that anti-pattern can bring to unexpected result:
Object.prototype.someCoolMethod = function(){ console.log('!') };
$.serializeObject({one: 'two'}) // => one=two&someCoolMethod=function%20(){%20console.log(%27!%27);%20}

I'l remove checks. But i've seen performance test `for in` vs. `forEach` and forEach was faster and looks better (and no need for 'own' check). I would replace all `for in` to the `Object.keys/forEach/map`. What you think?

**Pull request closed without merging**
