### PR TITLE
DataTable Checkbox for 'select all' should only select checkboxes in …

### PR DESCRIPTION
**Pull request by darrenjennings**
…associated column.

Fixes for #1562 

I've changed behavior so that column header checkboxes only select that column. If the column checkbox belongs to the first column, then it will toggle the "selected row" state by adding the associated class. Let me know what you guys think makes sense.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Looks good, thanks!

**Comment by AnotherAnkor** [comment]
can you givve a example of usage, please?

**Comment by darrenjennings** [comment]
@AnotherAnkor you can see an example in the PR for the kitchen sink, or maybe this fiddle will help you understand where you might want a checkbox in another column to not be affected by the first column. 
https://jsfiddle.net/vuc169w3/1/

**Comment by AnotherAnkor** [comment]
@darrenjennings looks nice and cool.
I did it like that:
`<li class="accordion-item">
                        <label class="label-checkbox item-content accordion-item-toggle">
                              <input type="checkbox" id="ks-attraction" name="ks-attraction" onChange="checkChecked(this)" value="1" checked>
                              <div class="item-media"><i class="icon icon-form-checkbox"></i></div>
                              <a href="#" class="item-link">
                                <div class="item-content">
                                  <div class="item-inner"> 
                                    <div class="item-title">
                                      Достопримечательности
                                    </div>
                                  </div>
                                </div>
                              </a>
                            </label>
                        <div class="accordion-item-content">
                          <ul>
                            <li class="first">
                              <label class="label-checkbox item-content">
                                  <input type="checkbox" id="museum" name="museum" class="ks-attraction" onChange="reCheck()" value="1" checked>
                                  <div class="item-media"><i class="icon icon-form-checkbox"></i></div>
                                  <a href="#" class="item-link" data-reload="true" data-ignore-cache="true" data-animate-pages="false">
                                    <div class="item-content">         
                                      <div class="item-title">
                                        Музеи и выставки
                                      </div>
                                    </div>
                                  </a>
                                </label>
                            </li>
                            <li class="first">
                              <label class="label-checkbox item-content">
                                  <input type="checkbox" id="places" name="places" class="ks-attraction" onChange="reCheck()" value="1" checked>
                                  <div class="item-media"><i class="icon icon-form-checkbox"></i></div>
                                  <a href="#" class="item-link" data-reload="true" data-ignore-cache="true" data-animate-pages="false">
                                    <div class="item-content">
                                      <div class="item-title">
                                        Исторические места и памятники
                                      </div>
                                    </div>
                                  </a>
                                </label></li>
                            <li class="first">
                              <label class="label-checkbox item-content">
                                  <input type="checkbox" id="parcs" name="parcs" class="ks-attraction" onChange="reCheck()" value="1" checked>
                                  <div class="item-media"><i class="icon icon-form-checkbox"></i></div>
                                  <a href="#" class="item-link" data-reload="true" data-ignore-cache="true" data-animate-pages="false">
                                    <div class="item-content">
                                      <div class="item-title">
                                        Парки
                                      </div>
                                    </div>
                                  </a>
                                </label></li>
                            <li class="first">
                              <label class="label-checkbox item-content">
                                    <input type="checkbox" id="temples" name="temples" class="ks-attraction" onChange="reCheck()" value="1" checked>
                                    <div class="item-media"><i class="icon icon-form-checkbox"></i></div>
                                    <a href="#" class="item-link" data-reload="true" data-ignore-cache="true" data-animate-pages="false">
                                      <div class="item-content">
                                        <div class="item-title">
                                          Храмы
                                        </div>
                                      </div>
                                    </a>
                                  </label>
                            </li>
                          </ul>
                        </div>
                      </li>`

In js: 
` function reCheck() {
    redraw();
    if ((document.getElementById("museum").checked==false) 
	&& (document.getElementById("places").checked==false) 
	&& (document.getElementById("parcs").checked==false)
	&& (document.getElementById("temples").checked==false) 
	&& (document.getElementById("ks-attraction").checked)) {
	document.getElementById("ks-attraction").checked=false;
    }; 
    
    if ((document.getElementById("museum").checked) 
	|| (document.getElementById("places").checked)
	|| (document.getElementById("parcs").checked) 
	|| (document.getElementById("temples").checked) 
	&& (!document.getElementById("ks-attraction").checked)) {
	document.getElementById("ks-attraction").checked=true;
    }; 
function checkChecked(param) {
    var flag = param.checked;
    var classname = param.id;
    for (var i = document.getElementsByClassName(classname).length - 1; i >= 0; i--) {
        document.getElementsByClassName(classname)[i].checked = flag;
    }
    redraw();
}; `
As you can see, looks horrible.
But nobody sayd me about functionality, what you showed.
In my case I need collapse and uncollapse subforms whith checkboxes. Because I have two layers <a target="_blank" href="https://itmages.ru/image/view/6031713/15d4eda5"></a>
Could you please explaine, how would you do it?

**Pull request merged**
