### PR TITLE
Allow template7 page rerendering

### PR DESCRIPTION
**Pull request by antono**
Its possible to update template7 pages with new data.

### CODE REVIEW

**Comment by ZanderBrown** [comment]
This looks to be of some interest. @valnub ?

**Comment by valnub** [comment]
@ZanderBrown Yeah, but Vladi knows F7 core rendering functionality better than me, so he'll have to decide if this gets merged.

**Comment by ZanderBrown** [comment]
@valnub sure, i was just going through the older issues/pr's and saw that this seemed to have gone unnoticed.

So @nolimits4web what do you think?

**Comment by J05HI** [comment]
@nolimits4web
Please add this. It's amazing!

**Comment by antono** [comment]
:+1:

**Comment by J05HI** [comment]
@nolimits4web 
What's up? Please merge it :)

**Comment by ZanderBrown** [comment]
@J05HI you will notice that there are merge conflicts, hence the red label

**Comment by J05HI** [comment]
Yeah then @antono should fix them

**Comment by J05HI** [comment]
I'll fork it and fix the merge conflicts.

**Comment by ZanderBrown** [comment]
@J05HI PR still has merge conflicts that @antono hasn't resolved

**Comment by J05HI** [comment]
@ZanderBrown 

You can close this now because of #1391.

**Comment by ZanderBrown** [comment]
Okay closing in favour of #1391

**Pull request closed without merging**
