### PR TITLE
Fix #575 - Change css links in examples and dist file

### LINKED ISSUE #575: Broken css links in examples and dist files
The css links are including `framework7.min.css` that no longer exists.
Should switch to `framework7.ios.min.css` or `framework7.material.min.css`

### PR DESCRIPTION
**Pull request by gagustavo**
Changed css links

### CODE REVIEW

**Comment by nolimits4web** [comment]
Thanks, but no changes should be committed to the `dist/` folder as it will modify the current release. If you revert changes from `dist/index.html` file, i will merge it

**Comment by gagustavo** [comment]
Reverted! Will you create new release to fix the mistake on download?

Thanks, Vlad!

**Comment by nolimits4web** [comment]
Thanks

**Comment by nolimits4web** [comment]
Yes, it will be already fixed in next release

**Pull request merged**
