### PR TITLE
Tap navbar scroll top

### PR DESCRIPTION
**Pull request by MarcGodard**
Implemented very common tap navbar to scroll to top of page.

Maybe we should add a param to turn this on and off, but many many apps
have it.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Need some improvements:
1) Parametrised and turned off by default
2) Should be also with click on statusbar-overlay
3) If clicked on "center" in navbar, need to check is there a link or not. Because there could be a link or tabs or something similar that shouldn't produce scroll top
4) This should cover all 3 navbar layout types
5) And finally :) Only currently active page should be scrolled top, not hidden ones

**Comment by MarcGodard** [comment]
Awesome, thanks, will make those changes after the weekend.

**Comment by nolimits4web** [comment]
Just found some time to implement it, should cover all usage cases

**Comment by MarcGodard** [comment]
Awesome. Thanks. Been busy with some work lately.

**Pull request closed without merging**
