### PR TITLE
fix ellipsis on navbar center text

### PR DESCRIPTION
**Pull request by GuillaumeBiton**
fix for Chrome and IE

### CODE REVIEW

**Comment by nolimits4web** [comment]
Yes, it will fix it in Chrome, but there is problem with it because if you put inside anything except it will not behave like it should, and `display:flex` has many advantages on `display:block` especially for something else instead of text, for example buttons

**Comment by GuillaumeBiton** [comment]
OK so I have try and there could be a fix with flex. Need to apply display: flex on .navbar and in .navbar.center remove display lines that enables flex. And it works too

**Comment by GuillaumeBiton** [comment]
Hi, do you want me to close this PR ?

**Comment by nolimits4web** [comment]
I think yes, we can close it for now

**Pull request closed without merging**
