### PR TITLE
Added subtitle for navbar center

### PR DESCRIPTION
**Pull request by etiennea**
Added subtitle for navbar center in iOS
Like in whatsup for example

Picture

### CODE REVIEW

**Comment by ZanderBrown** [comment]
Can you provide an example of this being used in an existing app as F7 should keep at close the the design guidelines as possible

**Comment by etiennea** [comment]
Whatsup and the official messages app too.

Although in the  official messages app the navbar become a few pixel higher.

**Comment by ZanderBrown** [comment]
@etiennea good call

**Comment by etiennea** [comment]
Twitter also uses it a lot. Many many apps use this pattern.

**Comment by JosephShenton** [comment]
image
Here is a preview of it i made some changes to it to look better also converted it to css but here is the css surely you know how to put it back into less

```
.center .subtitle {
    color: white;
    display: block;
    font-size: 12px;
    position: absolute;
    bottom: -13px;
    text-align: center;
    width: 100%;
    font-weight: bold;
}
```

**Comment by nolimits4web** [comment]
Merged, thanks!

**Pull request merged**
