### PR TITLE
Allows loading of old messages

### PR DESCRIPTION
**Pull request by MarcGodard**
Used with the infinite top scrolling this can load images from the top
of the messages.

Can also change the method if using a different library or can create a custom one.

infinittop

### CODE REVIEW

**Comment by nolimits4web** [comment]
Merged, but we still need option to have contra-versa logic with new messages on top/first, i will fix now

**Comment by nolimits4web** [comment]
Add some improvements to keep option with new messages on top, also fixed animation a bit, so the animation for top messages will be from top

**Comment by MarcGodard** [comment]
Very Nice.

**Comment by MarcGodard** [comment]
The only problem I see is that people will need to add and remove the class new-messages-first depending on if infinite scrolling is loading more or if they are typing and adding a new message on the bottom.

**Comment by nolimits4web** [comment]
Why? It is just adds another contra versa permanent scenario when you have new messages on top, old on bottom, and use of infinite scroll on bottom to load older messages

**Comment by MarcGodard** [comment]
Maybe, let me implement it and I will see.

**Pull request merged**
