### PR TITLE
:wrench: Issue #1387: Add an .editorconfig file

### PR DESCRIPTION
**Pull request by macdonst**
Adding in a .editorconfig file to cut down on issues when indenting and trailing whitespace when accepting PR's from other devs. Should make it easier to review PR's in the future.

### CODE REVIEW

**Comment by ZanderBrown** [comment]
How many editors respect `.editorconfig`?

**Comment by macdonst** [comment]
@ZanderBrown this many: http://editorconfig.org/#download

**Comment by nolimits4web** [comment]
Thanks!

**Comment by valnub** [comment]
Love this a lot ! Thanks :D

**Pull request merged**
