### PR TITLE
Check if touch moved before removing active state.

### PR DESCRIPTION
**Pull request by johnjamesjacoby**
Fixes issue causing active state on elements to be prematurely removed.

See #387.

### CODE REVIEW

**Comment by johnjamesjacoby** [comment]
See #387.

**Comment by nolimits4web** [comment]
Cool with first one, but can't accept this one https://github.com/johnjamesjacoby/Framework7/commit/9bd3f5bed49611bf62e4146f96526d0458b58000

It is a bit wrong, during touchmove event we still get distance in rendered pixels, not in physical, so you will just highly increase this distance, effects could be unintentional. So i think, it is better to leave it on developer decision, because you can always pass this parameter manually:
```
new Framework7({
  fastClicksDistanceThreshold: 10 * window.devicePixelRatio
})

**Comment by johnjamesjacoby** [comment]
That makes sense. Whatever you feel is best.

Happy to have that active state stuff sorted!

**Comment by nolimits4web** [comment]
Yep, so will you change the PR or you want me to merge it manually? Btw, do PR only in src/ files, not in dist/

**Comment by johnjamesjacoby** [comment]
Changed. Should be right now.

**Pull request merged**
