### PR TITLE
V2 Buttons

### PR DESCRIPTION
**Pull request by ZanderBrown**
Simple implementation of buttons

Probably imperfect

Stray thought:
Possibly use autoprefixer?

### CODE REVIEW

**Comment by ZanderBrown** [comment]
**This is work in progress**

**Comment by ZanderBrown** [comment]
#1602

**Comment by nolimits4web** [comment]
I see you have a bit wrong color-vars reference, -iOS, -md colors should be imported under HTML.ios, HTML.md rules in relevant files

**Comment by nolimits4web** [comment]
Merged, thanks!

**Pull request merged**
