### PR TITLE
Add autoFocus property to autocomplete

### PR DESCRIPTION
**Pull request by ZanderBrown**
Should present a better fix for #1349

Quite simple PR:
* add `autoFocus` boolean parameter
* update kitchen sink with examples

The docs will need updating accordingly 

Unfortunately the git history has gone a little weird throwing in a couple of merges

### CODE REVIEW

**Comment by ZanderBrown** [comment]
I suggest squash and merge for this one

**Comment by nolimits4web** [comment]
Looks good, but can you somehow revert commits to `dist/` files?

**Comment by ZanderBrown** [comment]
Okay i'll take a look

**Comment by nolimits4web** [comment]
@ZanderBrown i've merged it manually to avoid changes in `dist/` files with some additions. Thanks!

**Comment by ZanderBrown** [comment]
Thanks, i'll stop trying to bend Git to my will 😄

**Pull request closed without merging**
