### PR TITLE
Fixed buggy morph to popover animation for Chrome on Android

### PR DESCRIPTION
**Pull request by J05HI**
Fixed the bug with the morph to popover animation for Chrome on Android.
Fixes these issues: #1088, #885 

Here before & after video:
Before: [https://goo.gl/photos/pJzzFfaHcDGHbg2M9](https://goo.gl/photos/pJzzFfaHcDGHbg2M9)
After: [https://goo.gl/photos/sRbc773DzgNoBZsy6](https://goo.gl/photos/sRbc773DzgNoBZsy6)

### CODE REVIEW

**Comment by J05HI** [comment]
When do you integrate pull requests?

**Comment by valnub** [comment]
I think @nolimits4web is pretty busy currently and there are many other PRs waiting, so it might take some time until it's merged.

**Comment by J05HI** [comment]
Okay thank you for your fast response! :)

**Comment by ZanderBrown** [comment]
@J05HI unfortunately this PR has merge conflicts. Care to resolve them?

**Comment by J05HI** [comment]
No problem, I'll take a look

**Comment by J05HI** [comment]
Sorry, I had to open a new request: #1390

**Pull request closed without merging**
