### PR TITLE
Displays thumb on chrome

### PR DESCRIPTION
**Pull request by marcsoler**
Possible fix for Issue #929 
To be tested on Safari (have no Apple device)

fw7

### CODE REVIEW

**Comment by marcsoler** [comment]
**Update:** Tested on iOS Safari

**Comment by tobya** [comment]
@nolimits4web Is there any possibility of getting this issue merged in?

**Comment by nolimits4web** [comment]
The problem with this fix is that it will be broke thumbnail and range-fill on Safari (which is actually the target for iOS theme) where it works fine

**Comment by tobya** [comment]
@nolimits4web Thanks for the feedback we can make changes to fix to not break safari

**Comment by marcsoler** [comment]
@nolimits4web @tobya I've ran Tests (browserstack) on multiple iOS devices running Safari of course: Slider knob works.

iPhone 4s
bs_ios_mobile_iphone 4s 6 0 -6 0

iPad Mini
bs_ios_tablet_ipad mini-7 0

iPhone 6s
bs_realios_mobile_iphone 6s plus-9 0 1

What am I missing?

**Comment by ZanderBrown** [comment]
This good to merge now?

**Comment by nolimits4web** [comment]
Merged, thanks! Sorry for the delay

**Comment by tobya** [comment]
Great news @nolimits4web @marcsoler

**Comment by martinturner** [comment]
Sorry, im trying to use the slider now too, but i still see no thumb for the slider.
Is there a file i must change myself? 
I'm currently just using the code from the framework7.io page on forms. 
Thank you.

**Pull request merged**
