### PR TITLE
Fix for id #1056 (Wrong "style: left" on subnavbar in case of navbar with no right + subnavbar with left and right)

### PR DESCRIPTION
**Pull request by vyarmak**
When you have a navbar with icon on left and subnavbar with icons on left and right - size of is set according to navbar. That causes subnavbar to go to left.

Always follow the [contribution guidelines](https://github.com/nolimits4web/Framework7/blob/master/.github/CONTRIBUTING.md) when submitting a pull request.

### CODE REVIEW

**Comment by ZanderBrown** [comment]
@vyarmak could you explain further and clear up the merge conflicts please?

**Comment by akikochuchu** [comment]
Thank

**Comment by ZanderBrown** [comment]
@akikochuchu ?

**Comment by J05HI** [comment]
@akikochuchu
😂

**Comment by ZanderBrown** [comment]
With no explanation or response i plan to close this next weekend

**Comment by valnub** [comment]
@ZanderBrown Just smash the closing hammer 🤣  This PR is from summer last year.

**Pull request closed without merging**
